server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /docs-inator/ {
        try_files $uri $uri/ /index.html;
    }

    location = / {
        return 301 /docs-inator/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
