-- Retrofits tenant_id onto the four tables Phase 2/6 left ungoverned (documented gap, and a
-- confirmed P0 cross-tenant leak for the FAQ tables specifically): query_session_graph feeds
-- "People Also Asked" and the auto-FAQ generator, topic_subscriptions feeds proactive
-- notifications, and faq_clusters/faq_entries are the FAQ surface served (previously
-- unauthenticated) to every tenant alike.

-- query_session_graph: backfill from the owning chat session, same pattern as V11.
ALTER TABLE query_session_graph ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id);
UPDATE query_session_graph q SET tenant_id = s.tenant_id
    FROM chat_sessions s WHERE q.session_id = s.id AND q.tenant_id IS NULL;
ALTER TABLE query_session_graph ALTER COLUMN tenant_id SET NOT NULL;
CREATE INDEX idx_qsg_tenant ON query_session_graph(tenant_id, product, version, asked_at DESC);

-- topic_subscriptions: backfill from the owning user, same pattern as V11.
ALTER TABLE topic_subscriptions ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id);
UPDATE topic_subscriptions t SET tenant_id = u.tenant_id
    FROM users u WHERE t.user_id = u.id AND t.tenant_id IS NULL;
ALTER TABLE topic_subscriptions ALTER COLUMN tenant_id SET NOT NULL;
CREATE INDEX idx_topic_subs_tenant ON topic_subscriptions(tenant_id, product, version);

-- faq_clusters / faq_entries: unlike the tables above, any pre-existing rows here were
-- generated by clustering query text across ALL tenants at once — there is no single tenant to
-- attribute them to, so (unlike the rest of this migration) they are NOT backfilled. tenant_id
-- stays nullable at the DB level and every application read filters on an explicit tenant_id,
-- so old cross-tenant-blended rows simply become permanently unreachable rather than guessed at.
-- V11 already added tenant_id (backfilled to a default tenant) and a single-column
-- idx_faq_clusters_tenant index; replace that index with the composite one below, which
-- still covers tenant_id-only lookups as its leading column.
ALTER TABLE faq_clusters ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id);
DROP INDEX IF EXISTS idx_faq_clusters_tenant;
CREATE INDEX idx_faq_clusters_tenant ON faq_clusters(tenant_id, product, version, period_end DESC);

ALTER TABLE faq_entries ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id);
CREATE INDEX idx_faq_entries_tenant_status ON faq_entries(tenant_id, product, version, status);
