-- documentation_gap_reports: same reasoning as V20's faq_clusters/faq_entries — pre-existing
-- reports were generated by clustering query text across ALL tenants at once, so there is no
-- single tenant to backfill them to. tenant_id stays nullable at the DB level; every application
-- read filters on an explicit tenant_id, so old rows become unreachable rather than guessed at.
-- V11 already added tenant_id here and a single-column idx_gap_reports_tenant index; replace
-- that index with the composite one below, which still covers tenant_id-only lookups as its
-- leading column.
ALTER TABLE documentation_gap_reports ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id);
DROP INDEX IF EXISTS idx_gap_reports_tenant;
CREATE INDEX idx_gap_reports_tenant ON documentation_gap_reports(tenant_id, product, version, report_period_end DESC);

-- escalations and answer_upvotes predate tenancy and were never retrofitted. Both backfill
-- cleanly from their owning user, same pattern as V11/V21/V22.
ALTER TABLE escalations ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id);
UPDATE escalations e SET tenant_id = u.tenant_id
    FROM users u WHERE e.created_by = u.id AND e.tenant_id IS NULL;
ALTER TABLE escalations ALTER COLUMN tenant_id SET NOT NULL;
CREATE INDEX idx_escalations_tenant ON escalations(tenant_id, status, created_at DESC);

ALTER TABLE answer_upvotes ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id);
UPDATE answer_upvotes au SET tenant_id = u.tenant_id
    FROM users u WHERE au.user_id = u.id AND au.tenant_id IS NULL;
ALTER TABLE answer_upvotes ALTER COLUMN tenant_id SET NOT NULL;
CREATE INDEX idx_answer_upvotes_tenant ON answer_upvotes(tenant_id);

-- chunk_annotations: backfill from the chunk's own document, not the author, since the whole
-- point of an annotation is that it's scoped to the document it's attached to.
-- document_chunks/documents are owned by document-ingestor, not this service, and on a
-- genuinely fresh install documentation-bot migrates first (docker-compose has
-- document-ingestor wait on this service's health, not the reverse) — those tables may not
-- exist yet. chunk_annotations is guaranteed empty at that point too, so guard the backfill
-- rather than requiring ingestor's schema to already be present.
ALTER TABLE chunk_annotations ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id);
DO $$
BEGIN
    IF to_regclass('public.document_chunks') IS NOT NULL AND to_regclass('public.documents') IS NOT NULL THEN
        UPDATE chunk_annotations ca SET tenant_id = d.tenant_id
            FROM document_chunks dc JOIN documents d ON dc.document_id = d.id
            WHERE ca.document_chunk_id = dc.id AND ca.tenant_id IS NULL;
    END IF;
END $$;
ALTER TABLE chunk_annotations ALTER COLUMN tenant_id SET NOT NULL;
CREATE INDEX idx_chunk_annotations_tenant ON chunk_annotations(tenant_id);

-- audit_log: actor-scoped admin actions. Backfills from the actor; a handful of system-generated
-- entries with no actor (actor_id IS NULL) stay NULL and are simply excluded from every tenant's
-- view — they were never attributable to one tenant anyway.
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id);
UPDATE audit_log a SET tenant_id = u.tenant_id
    FROM users u WHERE a.actor_id = u.id AND a.tenant_id IS NULL;
CREATE INDEX idx_audit_log_tenant ON audit_log(tenant_id, created_at DESC);
